### ISSUE TITLE
Skapa layouten enligt skiss (dölj kalender på mobilvy) - (G)

### ISSUE THREAD

**Issue by Prisberg** [Prisberg/Miniprojekt#1]

**Comment by Prisberg** [comment]
Behöver komma fram till hur många js filer vi behöver utöver todos.js, calendar.js och today.js.

**Comment by Vacannot** [comment]
Vi gör så många JS filer som vi tycker behövs, det kan inte bli för många :)

Main fyller detta kravet nu base html + css samt lite media queries
